import type { CanonicalValue } from "./canonical.js";

/**
 * Structured simulator error. `code` is a stable identifier; `context` is
 * canonical data. Host messages and stacks are diagnostics only.
 */
export interface SimulationError {
  readonly code: string;
  readonly context: CanonicalValue;
}

/**
 * Stable codes from the draft specs. `SimulationError.code` remains `string`
 * so a later spec can add codes without a type break; this object is the
 * shared vocabulary.
 *
 * Modeled codes are delivered through a task `throw` or a `NetworkReply` body
 * and may be caught. All other listed codes terminate the run.
 */
export const ErrorCodes = {
  IDENTITY_OVERFLOW: "IDENTITY_OVERFLOW",
  SEQUENCE_OVERFLOW: "SEQUENCE_OVERFLOW",
  INVALID_RUN_INPUT: "INVALID_RUN_INPUT",
  INVALID_REGISTRATION: "INVALID_REGISTRATION",
  INVALID_OPERATION: "INVALID_OPERATION",
  STALE_CAPABILITY: "STALE_CAPABILITY",
  CONTROL_BUSY: "CONTROL_BUSY",
  INVALID_RUN_OPTIONS: "INVALID_RUN_OPTIONS",
  UNCONTROLLED_ASYNC: "UNCONTROLLED_ASYNC",
  SIMULATION_DEADLOCK: "SIMULATION_DEADLOCK",
  UNAWAITED_OPERATION: "UNAWAITED_OPERATION",
  INITIALIZATION_FAILED: "INITIALIZATION_FAILED",
  HANDLER_FAILED: "HANDLER_FAILED",
  INVALID_SIMULATION_TIME: "INVALID_SIMULATION_TIME",
  INVALID_DURATION: "INVALID_DURATION",
  TIME_OVERFLOW: "TIME_OVERFLOW",
  CLOCK_REWIND: "CLOCK_REWIND",
  NO_ACTIVE_TASK: "NO_ACTIVE_TASK",
  EVENT_IN_PAST: "EVENT_IN_PAST",
  INVALID_EVENT_TYPE: "INVALID_EVENT_TYPE",
  INVALID_EVENT_PAYLOAD: "INVALID_EVENT_PAYLOAD",
  INVALID_SCHEDULER_STATE: "INVALID_SCHEDULER_STATE",
  INVALID_OBSERVATION_FILTER: "INVALID_OBSERVATION_FILTER",
  INVALID_OBSERVATION_SCHEMA: "INVALID_OBSERVATION_SCHEMA",
  UNKNOWN_OBSERVATION_TYPE: "UNKNOWN_OBSERVATION_TYPE",
  INVALID_OBSERVATION: "INVALID_OBSERVATION",
  HISTORY_LIMIT_EXCEEDED: "HISTORY_LIMIT_EXCEEDED",
  HISTORY_SEALED: "HISTORY_SEALED",
  OBSERVER_REENTRANCY: "OBSERVER_REENTRANCY",
  INVALID_NETWORK_REQUEST: "INVALID_NETWORK_REQUEST",
  INVALID_NETWORK_REPLY: "INVALID_NETWORK_REPLY",
  NETWORK_TIMEOUT: "NETWORK_TIMEOUT",
  TARGET_UNAVAILABLE: "TARGET_UNAVAILABLE",
  ENDPOINT_NOT_FOUND: "ENDPOINT_NOT_FOUND",
  INVALID_MESSAGE_OPERATION: "INVALID_MESSAGE_OPERATION",
  BUS_CAPACITY_EXCEEDED: "BUS_CAPACITY_EXCEEDED",
  INVALID_DELIVERY: "INVALID_DELIVERY",
  INVALID_SERVICE_TRANSITION: "INVALID_SERVICE_TRANSITION",
  INVALID_CLIENT_ACTION: "INVALID_CLIENT_ACTION",
  INVALID_CLIENT_STATE: "INVALID_CLIENT_STATE",
  INVALID_EXTERNAL_CONFIGURATION: "INVALID_EXTERNAL_CONFIGURATION",
  EXTERNAL_UNAVAILABLE: "EXTERNAL_UNAVAILABLE",
  EXTERNAL_RATE_LIMITED: "EXTERNAL_RATE_LIMITED",
  INVALID_DATABASE_OPERATION: "INVALID_DATABASE_OPERATION",
  ROW_EXISTS: "ROW_EXISTS",
  ROW_NOT_FOUND: "ROW_NOT_FOUND",
  COMMIT_FAILED: "COMMIT_FAILED",
  TRANSACTION_CONFLICT: "TRANSACTION_CONFLICT",
  CONSTRAINT_VIOLATION: "CONSTRAINT_VIOLATION",
  INVALID_KV_OPERATION: "INVALID_KV_OPERATION",
  KV_NOT_INTEGER: "KV_NOT_INTEGER",
  KV_COUNTER_OVERFLOW: "KV_COUNTER_OVERFLOW",
  FAULT_PROBE_REUSED: "FAULT_PROBE_REUSED",
  INVALID_FAULT: "INVALID_FAULT",
  INVALID_SCENARIO: "INVALID_SCENARIO",
  INVALID_ASSESSMENT_RESULT: "INVALID_ASSESSMENT_RESULT",
} as const;

export type KnownErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Recoverable modeled failures. Reply-body codes are listed separately. */
export const ModeledErrorCodes = {
  NETWORK_TIMEOUT: ErrorCodes.NETWORK_TIMEOUT,
  BUS_CAPACITY_EXCEEDED: ErrorCodes.BUS_CAPACITY_EXCEEDED,
  ROW_EXISTS: ErrorCodes.ROW_EXISTS,
  ROW_NOT_FOUND: ErrorCodes.ROW_NOT_FOUND,
  COMMIT_FAILED: ErrorCodes.COMMIT_FAILED,
  TRANSACTION_CONFLICT: ErrorCodes.TRANSACTION_CONFLICT,
  CONSTRAINT_VIOLATION: ErrorCodes.CONSTRAINT_VIOLATION,
  KV_NOT_INTEGER: ErrorCodes.KV_NOT_INTEGER,
  KV_COUNTER_OVERFLOW: ErrorCodes.KV_COUNTER_OVERFLOW,
} as const;

/** Stable codes placed in `NetworkReply.body` rather than thrown as kernel errors. */
export const ReplyErrorCodes = {
  TARGET_UNAVAILABLE: ErrorCodes.TARGET_UNAVAILABLE,
  ENDPOINT_NOT_FOUND: ErrorCodes.ENDPOINT_NOT_FOUND,
  EXTERNAL_UNAVAILABLE: ErrorCodes.EXTERNAL_UNAVAILABLE,
  EXTERNAL_RATE_LIMITED: ErrorCodes.EXTERNAL_RATE_LIMITED,
} as const;

export function throwSimulationError(
  code: string,
  context: CanonicalValue = null,
): never {
  throw Object.assign(new Error(code), { code, context } satisfies SimulationError);
}
